# Generated by Django 6.0.6 on 2026-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
